version: '3'
services:
  mongodb:
    image: 'mongo'
    container_name: 'todo-mongo-container'
    environment:
      - MONGO_INITDB_DATABASE=todo_db
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:Z
      - ./mongo-volume:/data/db:Z
